### ISSUE TITLE
Update  com.microsoft.projectoxford:face:1.2.1 to 1.2.2

### ISSUE THREAD

**Issue by malnakli** [Microsoft/Cognitive-Face-Android#10]
Could you please push the latest changes to http://search.maven..org/?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.microsoft.projectoxford%22%20AND%20a%3A%22face%22

**Comment by huxuan** [comment]
Hi @malnakli, we have already working on that. I will keep this issue open until it is done. One thing I can reveal is that new version number will be 1.2.5. Thanks for your attention and patient. :-)

**Comment by huxuan** [comment]
Close as 1.2.5 is available now.

http://search.maven.org/#artifactdetails%7Ccom.microsoft.projectoxford%7Cface%7C1.2.5%7Caar

**Comment by malnakli** [comment]
Thank you @huxuan
