### ISSUE TITLE
I have problem with detecting face. It may has problem with the key.

### ISSUE THREAD

**Issue by hady13** [Microsoft/Cognitive-Face-Android#12]
I'm trying to detect and draw a rectangle frame in a picture (in drawable folder) just for testing this API is working well in my project. But it doesn't work like this. I have log '11111111111111111111111111' in Android Monitor that means the 'face == null'....
![face](https://cloud.githubusercontent.com/assets/11660797/25264026/df712e8c-269e-11e7-8820-f1fa7cbedc29.JPG)

please help me..!

**Comment by hady13** [comment]
![err](https://cloud.githubusercontent.com/assets/11660797/25303474/ade5cce2-278e-11e7-9312-01551cd35496.JPG)
oh.. I found this error...!
I'm cooperating with my friend, so we have to share this code. But, I think this key make prevent it.
What was worse, it worked at the very beginning! I don't know how to solve this problem..

**Comment by huxuan** [comment]
Maybe you can have a try on seek the file to 0 before sending the image?

**Comment by hady13** [comment]
What it means 'file to 0'? Could you explain more precisely, please?

**Comment by huxuan** [comment]
You need to set the file pointer to the beginning for reading it again. Maybe this stackoverflow link [1] can explain it better.

[1] http://stackoverflow.com/questions/2226699/how-can-i-reset-the-file-pointer-to-the-beginning-of-the-file-in-java

**Comment by PriyaThakur** [comment]
Facing the same issue! Says invalid subscription key. Could you guys let me know how you fixed it?

**Comment by huxuan** [comment]
@PriyaThakur Invalid subscription key is a different problem. Please open a new issue and provide more specific information about your problem to get more effective help.

**Comment by huxuan** [comment]
Might be a problem related to #15 which is fixed in #17.
Please feel free to reopen it if you have any further questions.
