### ISSUE TITLE
facelist.faceGroupId not set

### ISSUE THREAD

**Issue by scriptomat** [Microsoft/Cognitive-Face-Android#14]
When reading all face lists with FaceServiceRestClient.listFaceLists(), an array of FaceListMetadata objects is returned. But the attribute faceGroupId is null on all objects. This id is necessary to delete such a list.

Is it a naming problem? faceGroupId/faceListId?

**Comment by huxuan** [comment]
Yep, I think you are right.
Can you help to confirm the fixing by changing the `faceGroupId` to `faceListId`?
A pull request will be warm welcome. :-)

**Comment by huxuan** [comment]
This should be fixed by pull request #20 . Feel free to reopen it if there is any further questions.
