### ISSUE TITLE
I have NullPointerException with createPerson.

### ISSUE THREAD

**Issue by hady13** [Microsoft/Cognitive-Face-Android#18]
![image](https://cloud.githubusercontent.com/assets/11660797/26750840/ac94284a-4866-11e7-8cec-fc8d8a470bf0.png)

Hi, I'm using this API for my application.
I wanna use the method 'createPerson' as the top image, but I got the NullPointerException like this.

![image](https://cloud.githubusercontent.com/assets/11660797/26750794/b09f4aba-4865-11e7-981b-0c75dd8c3932.png)

The exception line 45 is on ①, and the line 24 is on ② that I wrote with red pen.. (the line number is not excactly equal with the top image, because I delete annotation for capture.)

I wrote the class and method the same as with Sample App.. but I don't know why this happens..
Please help me! T-T

**Comment by hady13** [comment]
oh... I got it..!
It was because of "SampleApp.getFaceServiceClient()"..
Instead of this, I should put my subscriptionkey here..!

**Comment by mohammed-adil-moughal** [comment]
hey put your substription key where
