### ISSUE TITLE
Face API - Adding image to a group not saving

### ISSUE THREAD

**Issue by Phumba2** [Microsoft/Cognitive-Face-Android#21]
All are working except when I use the Identification Button. I was able to add a Group and also able to add Persons within the group and they get saved. However, when i start to add the images for Person A, emulator will show the image but when I click Save, the image did not get added to Person A. It is not getting saved.  The download of this app was as of **June 6, 2017**.  See the screenshot.
![faceapi4](https://user-images.githubusercontent.com/28742171/26896056-951dcbb6-4b91-11e7-9a28-363af4bb7825.jpg)
Any help is appreciated.
Thanks

**Comment by huxuan** [comment]
Hi @Phumba2, let us keep the issue to stackoverflow: https://stackoverflow.com/questions/44376797/microsoft-face-api-in-android
