### ISSUE TITLE
Person group training status is Failed

### ISSUE THREAD

**Issue by JunjieCheng** [Microsoft/Cognitive-Face-Android#24]
In the log, I saw that the person group has been successfully trained, but when I tried to identify a photo, it shows warning "Person group training status is Failed".

**Comment by huxuan** [comment]
Any more specific error message from `GetTrainingStatus`?

**Comment by JunjieCheng** [comment]
I only tried the sample. I will tell you later after I write the App by myself.

**Comment by JunjieCheng** [comment]
I have figured out that. It is because I didn't select the face, so the person contains nothing.

**Comment by huxuan** [comment]
Close as problem solved.
