### ISSUE TITLE
AddFaceToPersonActivity: AsyncTask executed in onResume 

### ISSUE THREAD

**Issue by JunjieCheng** [Microsoft/Cognitive-Face-Android#25]
In the Sample code AddFaceToPersonActivity, I saw that DetectionTask is executed in onResume but not onCreate. I can't understand how does it work. Can you please help me?

`@Override
    protected void onResume() {
        super.onResume();

        Uri imageUri = Uri.parse(mImageUriStr);
        mBitmap = ImageHelper.loadSizeLimitedBitmapFromUri(
                imageUri, getContentResolver());
        if (mBitmap != null) {
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            mBitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);
            InputStream imageInputStream = new ByteArrayInputStream(stream.toByteArray());
            addLog("Request: Detecting " + mImageUriStr);
            new DetectionTask().execute(imageInputStream);
        }
    }`

**Comment by huxuan** [comment]
I do not think there is any specific reason to do that. The sample aims to be a showcase for the usage of Face API Android SDK, there is no special design and the quality may not be so mature. As this is more like an Android specific problem, I will close this issue.
