### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by mohammed-adil-moughal** [Microsoft/Cognitive-Face-Android#29]
am getting the follow error attempt to invooke
![image](https://user-images.githubusercontent.com/10894677/35139310-94646756-fd03-11e7-8262-5e845418b9f2.png)
the sample app code is
![image](https://user-images.githubusercontent.com/10894677/35139342-be207da0-fd03-11e7-859d-ddefb7ed5352.png)
kindly assist

**Comment by cthrash** [comment]
The first step is to make sure `SampleApp.onCreate` is called.  Is it?

**Comment by huxuan** [comment]
Seems the endpoint is wrong? It should be something like `https://westcentralus.api.cognitive.microsoft.com/face/v1.0/`.

Please also mind the region value is corresponding with the subscription key.
