### ISSUE TITLE
Does the readme reference an out of date version of the client library?

### ISSUE THREAD

**Issue by mtaulty** [Microsoft/Cognitive-Face-Android#30]
The doc page says to use;

compile 'com.microsoft.projectoxford:face:1.1.0'

whereas the current version seems to be 1.3 and using 1.1 means that lots of facial features (e.g. noise, blur) don't show up in the client library.

**Comment by huxuan** [comment]
Hi @mtaulty, thanks for the reporting. Do you mean the `README.md` of this repo? I have to admit the doc is a little outdated, we are going to fix it in the next release. You are also free to send a pull request if you wish. I will keep this pull request open until the problem is solved.

**Comment by huxuan** [comment]
Closed as the README is updated.
