### ISSUE TITLE
How to merge two microsoft sample apps

### ISSUE THREAD

**Issue by zallia2** [Microsoft/Cognitive-Face-Android#32]
How can I join https://github.com/Microsoft/Cognitive-Vision-Android with https://github.com/Microsoft/Cognitive-Face-Android so that both apps are combined into one. As I was looking to make an app which combined both technologies to help blind people familiarise themselves with certain things by letting them know what it is. Can you please send me the file/folder with the solution by providing a link to it and how and where I can use it as I'm pretty new to android app development. When someone provides the code I need to know where to add it and test it that it works. So basically I am trying to create a similar app to Seeing AI. All help is well appreciated. Thanks

**Comment by huxuan** [comment]
Those samples is not product level applications, they only shows how to leverage corresponding Android SDK of Cognitive Services. From my point of view, you can just look into the code snippets where invoking the Android interfaces and do similar things in your own app, that should be OK.

Does that answer you questions? Please feel free to pump up if there is any further questions.

**Comment by huxuan** [comment]
Close as there is no further response.
