### ISSUE TITLE
about

### ISSUE THREAD

**Issue by 330132662** [Microsoft/Cognitive-Face-Android#35]
if I use the dependency of  'compile 'com.microsoft.projectoxford:face:1.4.1'' ,  when the android-studio was building it ,it told me 'Error:(15) error: unknown element <library> found.' ,then I delete the dependency   of '    compile 'com.microsoft.projectoxford:face:1.4.1''  ,and use the local module lib ,it was ok!

**Comment by 330132662** [comment]
不是  您是中国人啊 。。那个您的commit日志我看到了 ，移除了library ，哈哈

**Comment by 330132662** [comment]
@huxuan 
   我在strings里 填写了申请的key ， 跑器demo之后 还是提示  无效的subscription key。。

**Comment by huxuan** [comment]
@330132662 请确认一下对应的endpoint是否正确，默认对应的是westus的。

**Comment by 330132662** [comment]
@huxuan    demo 已正常运行  感谢前辈指导！

**Comment by huxuan** [comment]
Closed as problem resolved.
