### ISSUE TITLE
我。。又来了，关于两张人脸对比那个activity的字符编码问题 

### ISSUE THREAD

**Issue by 330132662** [Microsoft/Cognitive-Face-Android#36]
FaceVerificationActivity，  进行验证的时候

‘@Override
        protected VerifyResult doInBackground(Void... params) {
            // Get an instance of face service client to detect faces in image.
            FaceServiceClient faceServiceClient = SampleApp.getFaceServiceClient();
            try {
                publishProgress("Verifying...");

                // Start verification.
                return faceServiceClient.verify(
                        mFaceId0,      /* The first face ID to verify */
                        mFaceId1);     /* The second face ID to verify */
            } catch (Exception e) {
                publishProgress(e.getMessage());  // 在这里 出现了异常java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]
                addLog(e.getMessage());
                return null;
            }
        }
···

出现了异常java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]，我发现两个faceid都不是string类型，无从下手了  请问我该如何处理

**Comment by huxuan** [comment]
It should be UUID rather than string.

Please note that we have limited bandwidth to provided technical support for Android SDK.
Android/Java Programming Language seems to be out of scope.

**Comment by 330132662** [comment]
抱歉啊，我已经找到问题所在，这个问题是因为我没用最新的1.4.3   ..已经解决了 ，感谢您的回复！
