### ISSUE TITLE
Microsoft-Cognitive add new person with chinese name

### ISSUE THREAD

**Issue by ShenTw** [Microsoft/Cognitive-Face-Android#38]
After I import 1.4.2 arr file in my project, I even got **'java.nio.charset.CharsetICU[UTF-8]'** exception when I use faceServiceClient.identity ! I originally could use this function at 1.4.1 version @@
`faceServiceClient.identity(
                        this.mPersonGroupId, 
                        uuids,  
                        1);`
 And got **java.io.UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]** when I use `faceServiceClient.trainPersonGroup(groupName[0]);`

**Comment by ShenTw** [comment]
![image](https://user-images.githubusercontent.com/16998576/38783753-314a337e-4139-11e8-99d4-970854080ca6.png)

**Comment by huxuan** [comment]
@ShenTw The new version will be released soon. Just be a little patient.

**Comment by ShenTw** [comment]
@huxuan Sorry for my rudeness : ) I just wondered whether I got wrong place to download the new version. Thanks for your reply. I will look forward to the new version : )

**Comment by ShenTw** [comment]
@huxuan  Thank you very much. I have downloaded the newest version (1.4.3) and solved my problem!!
Thanks a lot. : )

**Comment by huxuan** [comment]
Nice to hear. Then I will close this issue as problem solved.
