### ISSUE TITLE
Actual API Level Requirement

### ISSUE THREAD

**Issue by jinfeei** [Microsoft/Cognitive-Face-Android#40]
It is stated:

"Android OS must be Android 4.1 or higher (API Level 16 or higher)." However, to use the library (as described) an API level of at least 22 is required!

Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 22 declared in library [com.microsoft.projectoxford:face:1.4.3] C:\Users\Jeffrey\.gradle\caches\transforms-1\files-1.1\face-1.4.3.aar\c27440009e99f6447afc74ec8bfeed96\AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 22,
		or use tools:overrideLibrary="com.microsoft.projectoxford.face" to force usage (may lead to runtime failures)

**Comment by carlosgub** [comment]
I think is already fixed because I download the last version fo the app and I see minSdkVersion to 22 :D.

**Comment by lebronJ** [comment]
Thanks for pointing out. And since #44 has been merged, this is auto solved.
