### ISSUE TITLE
Importing the project into android studio

### ISSUE THREAD

**Issue by krishna1990fis** [Microsoft/Cognitive-Face-Android#5]
i have downloaded the code from github, it has sample, data, client library . i am bit confused which part to import in my android studio. i tried importing sample part but it was throwing lot of errors while building the project. Please suggest me how to import it properly so that i can be able to run the code properly to see the FACE API demo.

Thanks in advance,
Krishna P

**Comment by alexbance** [comment]
You wouldn't want to import the client library as you should be referencing that as a dependency, either by directly adding it to the build path or using Maven/Gradle to resolve it for you. To import the sample select the "import from Gradle" option and set the root directory to the "Sample" folder.

Also I'm not sure why you have created two issues about the same thing?

**Comment by krishna1990fis** [comment]
thanks for replying, following are the problems i am facing
1. as u said, their is no import from gradle option in my android studioo
![image](https://cloud.githubusercontent.com/assets/16776975/20745893/47291f5e-b709-11e6-802c-b1ed8ce39017.png)
2. as u said, i am just trying to import the sample folder.
![image](https://cloud.githubusercontent.com/assets/16776975/20745944/89cf167e-b709-11e6-8896-14e357b17a48.png)
3. after importing the project, this is what the error im getting
![image](https://cloud.githubusercontent.com/assets/16776975/20746018/e4429450-b709-11e6-87ad-03c11a57a371.png)
4. also after importing the project, the project structure does not seem to be correct.
Please answer these questions to get me started. i am working on this for the first time, so please bare with my little knowledge on these things.

and also i apologise for creating two issues for the same problem

Thank you so much
Krishna

**Comment by alexbance** [comment]
Can you try importing the project by selecting the "settings.gradle" file as shown in following image.
![image](https://cloud.githubusercontent.com/assets/23360105/20748549/8524cc40-b6e6-11e6-9043-69beaeb68bde.png)

**Comment by YDrall** [comment]
or you can try this(it worked for me):
Go to file->New->Import Project
then select sample folder of the repository.

**Comment by huxuan** [comment]
Close as the the thread is too old. If you encounter similar problem, please open a new one as the code might changed a lot.
