### ISSUE TITLE
hostname in certificate didn't match: <westus.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

### ISSUE THREAD

**Issue by jatin-lakhani** [Microsoft/Cognitive-Face-Android#52]

**Comment by jatin-lakhani** [comment]
Face detection api gives error in samsung devices. It works with other device but getting error in samsung device only

The following error shows in log :
hostname in certificate didn't match: <westus.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

please help me on this.

**Comment by vernazza** [comment]
Same problem here, with error
 javax.net.ssl.SSLException: hostname in certificate didn't match: <eastus2.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

**Comment by vernazza** [comment]
The problem is due to a change in the certificates on MS side.
The library uses a deprecated & outdated org.apache httpClient that doesn't support SNI headers. (see #50)

**Comment by lebronJ** [comment]
Thanks @vernazza for the contribution, with that PR #53 merged, this should be fixed. Feel free to reopen this if you still meet similar problems.
