### ISSUE TITLE
Face Verification

### ISSUE THREAD

**Issue by Unic-1** [Microsoft/Cognitive-Face-Android#9]
When we select first photo and then try to select the second photo the previous photo gets removed so the verify button is not getting enabled. And also selecting any button after the selection of the photo will remove the selected photo
Please kindly give a solution to this.

**Comment by huxuan** [comment]
We failed to reproduce the problem on the lastest version, would you please help us to confirm it?

Close currently and feel free to reopen it if same error still exists.
